### ISSUE TITLE
Multi Search Should Provide Multiple Tabs

### ISSUE THREAD

**Issue by freddysilber** [siddheshranade/combined-search#6]
When I search with more than one checkbox checked, only the first one opens. It would be nice if everything checked popped up. 

What do you think?

**Comment by siddheshranade** [comment]
I think you need to manually enable popups at least once. By default it opens only the first website and blocks the others. Once popups are enabled, all will open. Let me know if I can help further.

**Comment by freddysilber** [comment]
Fair enough!

In my opinion it would be nice if the user didn't have to change settings in their browser to use this app.

Do you think that there might be another way to make this possible?

Would it be a good idea to implement another 'setting' to enable multiple tabs opening on a 'search'?

**Comment by siddheshranade** [comment]
You're right. I looked quite hard for a non popup option when I was working on this but couldn't find a workaround. I almost considered not shipping this because of that annoyance. So far, as much as I can tell, executing multiple `window.open()` function calls cannot be done without popups.

I'm not sure how another setting to enable multiple tabs would work differently. Do elaborate (or submit a PR) if you have an idea on how it should look.
